name: 'Terraform Pipeline Demo'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT

jobs:
  ci-cd-tf:
    name: 'CI/CD Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.15.2"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: arn:aws:iam::490874679766:role/github-role
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
